// <auto-generated />
namespace WebShoppingOnline.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_alias_in_ProductCategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_alias_in_ProductCategory));
        
        string IMigrationMetadata.Id
        {
            get { return "202306041025471_update_alias_in_ProductCategory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
